# Generated by Django 5.2.3 on 2025-07-04 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('duracao_horas', models.PositiveIntegerField(verbose_name='Duração (horas)')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('telefone_cliente', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_inicio_atendimento', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('lead_novo', 'Lead Novo'), ('contato', 'Contato Feito'), ('visita', 'Visita Agendada'), ('matricula', 'Matriculado'), ('perdido', 'Perdido'), ('visita_agendada_compareceu', 'Visita Agendada - Compareceu'), ('visita_agendada_faltou', 'Visita Agendada - Faltou')], default='lead_novo', max_length=40)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ad_whats', models.BooleanField(default=False, verbose_name='Adicionado no WhatsApp')),
                ('atendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cursos_interesse', models.ManyToManyField(blank=True, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='LeadObservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_observacoes', to='core.lead')),
            ],
        ),
    ]
