# Generated by Django 5.2.3 on 2025-06-30 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='curso_interesse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curso'),
        ),
    ]
