# Generated by Django 5.2.3 on 2025-07-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lead_curso_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('lead_novo', 'Lead Novo'), ('contato', 'Contato Feito'), ('visita', 'Visita Agendada'), ('matricula', 'Matriculado'), ('perdido', 'Perdido'), ('VISITA_AGENDADA_COMPARECEU', 'Visita Agendada - Compareceu'), ('VISITA_AGENDADA_FALTOU', 'Visita Agendada - Faltou')], default='lead_novo', max_length=40),
        ),
    ]
