# Generated by Django 5.2.3 on 2025-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='curso_interesse',
        ),
        migrations.AddField(
            model_name='lead',
            name='cursos_interesse',
            field=models.ManyToManyField(blank=True, related_name='leads', to='core.curso'),
        ),
    ]
