# Generated by Django 5.2.3 on 2025-07-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_lead_curso_interesse_lead_cursos_interesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='cursos_interesse',
            field=models.ManyToManyField(blank=True, to='core.curso'),
        ),
    ]
