# Generated by Django 5.2.3 on 2025-07-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_lead_cursos_interesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ad_whats',
            field=models.BooleanField(default=False, verbose_name='Adicionado no WhatsApp'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('lead_novo', 'Lead Novo'), ('contato', 'Contato Feito'), ('visita', 'Visita Agendada'), ('matricula', 'Matriculado'), ('perdido', 'Perdi do'), ('VISITA_AGENDADA_COMPARECEU', 'Visita Agendada - Compareceu'), ('VISITA_AGENDADA_FALTOU', 'Visita Agendada - Faltou')], default='lead_novo', max_length=40),
        ),
    ]
